# Enable Home Assistant API
api:
  encryption:
    key: ${esplink_microvpn_privatekey}

time:
  - platform: sntp

wireguard:
  # User Configuration
  private_key: ${esplink_microvpn_privatekey}
  address: ${esplink_microvpn_address}

  # ESPLink Supplied Configuration
  peer_endpoint: ${esplink_microvpn_namespace}.vpn.esplink.app
  peer_public_key: !include keys/${esplink_microvpn_namespace}.pub
  peer_persistent_keepalive: 15s
  <<: !include configs/${esplink_microvpn_namespace}.yaml
